# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from  pyqtgraph import PlotWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(5, 21, 421, 481))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(440, 20, 376, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.rectYLeft = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.rectYLeft.setObjectName("rectYLeft")
        self.gridLayout.addWidget(self.rectYLeft, 7, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 10, 0, 1, 2)
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 4, 0, 1, 2)
        self.lengthEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lengthEdit.setObjectName("lengthEdit")
        self.gridLayout.addWidget(self.lengthEdit, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.sectionButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sectionButton.setObjectName("sectionButton")
        self.gridLayout.addWidget(self.sectionButton, 11, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 2)
        self.widthEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.widthEdit.setObjectName("widthEdit")
        self.gridLayout.addWidget(self.widthEdit, 9, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 8, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 1, 1, 1)
        self.rectXLeft = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.rectXLeft.setObjectName("rectXLeft")
        self.gridLayout.addWidget(self.rectXLeft, 7, 0, 1, 1)
        self.linesEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.linesEdit.setObjectName("linesEdit")
        self.gridLayout.addWidget(self.linesEdit, 1, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 2)
        self.linesTableButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.linesTableButton.setObjectName("linesTableButton")
        self.gridLayout.addWidget(self.linesTableButton, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Построить отрезки и прямоугольник"))
        self.label_3.setText(_translate("MainWindow", "Верхний левый угол по у"))
        self.label_2.setText(_translate("MainWindow", "Верхний левый угол по х"))
        self.sectionButton.setText(_translate("MainWindow", "Отсечь"))
        self.label_6.setText(_translate("MainWindow", "Введите координаты отрезков"))
        self.label.setText(_translate("MainWindow", "Введите параметры прямоугольника"))
        self.label_4.setText(_translate("MainWindow", "Длина"))
        self.label_5.setText(_translate("MainWindow", "Ширина"))
        self.label_7.setText(_translate("MainWindow", "Введите количество отрезков"))
        self.linesTableButton.setText(_translate("MainWindow", "Ввести координаты отрезков"))
from pyqtgraph import PlotWidget
